---

- hosts: mullen_production
  user: ubuntu
  sudo: yes

  tasks:
    - name: 3. Create a new database
      mysql_db: name=test_ansible_db state=present collation=utf8_general_ci


    - name: 4. Create a database user
      mysql_user: name=testuser password=test1ng priv=*.*:ALL host=localhost state=present


  handlers:
    - name: restart mariadb
      action: service name=mysql state=restarted



    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: copy .my.cnf file with root password credentials
      template: src=templates/my.cnf dest=/root/.my.cnf owner=root mode=0600