---

- hosts: mullen_production
  user: ubuntu
  sudo: yes

  tasks:
    - name: 3. Create a new database
      mysql_db: name=test_ansible_db state=present collation=utf8_general_ci


    - name: 4. Create a database user
      mysql_user: name=testuser password=test1ng priv=*.*:ALL host=localhost state=present


  handlers:
    - name: restart mariadb
      action: service name=mysql state=restarted
