---

- hosts: garnish
  user: tom
  sudo: yes

  tasks:

    - name: install initial packages
      action: apt pkg=$item state=installed
      with_items:
        - build-essential
        - python-software-properties
        - htop
        - vim-nox
        - ufw

    - name: add nginx and node ppas
      action: apt_repository repo=$item state=present
      with_items:
        - ppa:chris-lea/node.js
        - ppa:nginx/stable

    - name: add postgresql repo
      action: apt_repository repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

    - name: install main packages for python node nginx and postgresql
      action: apt pkg=$item state=installed
      with_items:
        - libpq-dev
        - libmysqlclient-dev
        - libxml2-dev
        - libjpeg62
        - libjpeg62-dev
        - libfreetype6
        - libfreetype6-dev
        - zlib1g-dev
        - mysql-client
        - python-dev
        - python-setuptools
        - python-imaging
        - python-mysqldb
        - python-psycopg2
        - git-core
        - nginx
        - nodejs
        - postgresql
        - libpq-dev
        - python-dev

    - name: install pip
      action: easy_install name=pip

    - name: install various libraries with pip
      action: pip name=$item state=present
      with_items:
        - virtualenv
        - supervisor
        - uwsgi
        - psycopg2

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libfreetype.so dest=/usr/lib/libfreetype.so state=link

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libz.so dest=/usr/lib/libz.so state=link

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libjpeg.so.62 dest=/usr/lib/x86_64-linux-gnu/libjpeg.so state=link

    - name: symlink imaging library files
      action: file src=/usr/lib/x86_64-linux-gnu/libjpeg.so dest=/usr/lib/libjpeg.so state=link

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: write nginx.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf

    - name: create supervisord config folder
      action: file dest=/etc/supervisor state=directory owner=root

    - name: create supervisord config
      action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

    - name: create supervisord init script
      action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

    - name: start supervisord service and have it run during system startup
      action: service name=supervisord state=started enabled=yes

    - name: create webapps directory
      action: file dest=/srv/webapps state=directory

    - name: add postgres user to admin group
      action: user name=postgres groups=admin append=yes

    - name: update postgres db configuration
      action: copy src=templates/postgresql.conf dest=/etc/postgresql/9.2/main/postgresql.conf
      notify:
        - restart postgresql

    - name: update postgres client configuration
      action: copy src=templates/pg_hba.conf dest=/etc/postgresql/9.2/main/pg_hba.conf
      notify:
        - restart postgresql

  handlers:
    - name: restart postgresql
      action: service name=postgresql state=restarted
